name: weather_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.0.1
  flutter_bloc: ^6.0.1
  chopper: ^3.0.2
  connectivity: ^0.4.3+2
  json_annotation: ^3.0.1
  built_value: ^6.7.0
  flutter_screenutil: ^4.0.2+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  chopper_generator: ^3.0.4
  #  built_value_generator: ^6.7.0
  # No version number means the latest version
  build_resolvers: ^1.3.11
  build_runner: ^1.9.0
  json_serializable: ^3.5.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/
